### ISSUE TITLE
Compatibility with newer Python version

### ISSUE THREAD

**Issue by QuantumQuill** [jongan69/Redbubble_Uploader#10]
Can you please upgrade to latest Python Version?

```
Cannot install -r requirements.txt (line 2) and wrapt==1.12.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested wrapt==1.12.1
    astroid 2.15.5 depends on wrapt<2 and >=1.14; python_version >= "3.11"
```

**Comment by jongan69** [comment]
I tried updating the code but the issues with Cloudflare seem to make this code maintenance unfeasible at his time, if you need further help open a new issue and I will review but this code should honestly be rebuilt with poetry or Conda for stable environment dependencies.
