### ISSUE TITLE
CloudFlare Blocker doesn't Work

### ISSUE THREAD

**Issue by mjidelouss** [jongan69/Redbubble_Uploader#11]
Can't bypass CloudFlare i fixed that but now the email field isn't captured for some reason.

**Comment by PLFR23456** [comment]
how did you bypass please ?

**Comment by mjidelouss** [comment]
if i memory serves me well i think i used a different browser library

**Comment by PLFR23456** [comment]
do you think you could send me your code with the correction? it could really help me pls :)

**Comment by mjidelouss** [comment]
i want to bro but i cleaned out my computer 2 months ago. its gone

**Comment by jongan69** [comment]
If someone wants to rebuild this I made a video on trying again, Cloud flare is blocking based on what appears to be an SSL issue, the bot isn't a user and chrome knows that so I think Cloudflare steps in. Maybe a jest test on a logged in user could work better at this point.
