### ISSUE TITLE
While installing the pywatchman there is an error is displaying

### ISSUE THREAD

**Issue by yazhamuthan-aruchamy** [jongan69/Redbubble_Uploader#7]
Collecting pywatchman
  Using cached pywatchman-1.4.1.tar.gz (29 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: pywatchman
  Building wheel for pywatchman (setup.py): started
  Building wheel for pywatchman (setup.py): finished with status 'error'
  Running setup.py clean for pywatchman
Failed to build pywatchman
Installing collected packages: pywatchman
  Running setup.py install for pywatchman: started
  Running setup.py install for pywatchman: finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [15 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\capabilities.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\compat.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\encoding.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\load.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\pybser.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\__init__.py -> build\lib.win-amd64-cpython-310\pywatchman
  running build_ext
  building 'pywatchman.bser' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pywatchman
  error: subprocess-exited-with-error
  
  Running setup.py install for pywatchman did not run successfully.
  exit code: 1
  
  [17 lines of output]
  running install
  D:\Python files\undetected-chromedriver-master\venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\capabilities.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\compat.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\encoding.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\load.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\pybser.py -> build\lib.win-amd64-cpython-310\pywatchman
  copying pywatchman\__init__.py -> build\lib.win-amd64-cpython-310\pywatchman
  running build_ext
  building 'pywatchman.bser' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

pywatchman

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

i Don't know how to install it, I am using pycharm do i need to use some other tools for this  ?

**Comment by jongan69** [comment]
I tried updating the code but the issues with Cloudflare seem to make this code maintenance unfeasible at his time, if you need further help open a new issue and I will review but this code should honestly be rebuilt with poetry or Conda for stable environment dependencies.

**Comment by jongan69** [comment]
Also, your issue seems to need to C/C++ tools for chrome driver to work, I've been thinking this would be better as a jest test locally run but I would need to experiment. Feel free to open a new issue if you need.
